services:
  cojakeons-plus:
    image: ghcr.io/slmingol/cojakeons-plus:latest
    container_name: cojakeons-plus
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - cojakeons-network

networks:
  cojakeons-network:
    driver: bridge
