services:
  conjakeons-plus:
    image: ghcr.io/slmingol/conjakeons-plus:latest
    container_name: conjakeons-plus
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - conjakeons-network

networks:
  conjakeons-network:
    driver: bridge
